name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      wiremock:
        image: wiremock/wiremock:2.35.0
        ports:
          - 8080:8080
        options: --health-cmd="curl --silent --fail http://localhost:8080/__admin/health" --health-interval=10s --health-timeout=5s --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

  test:
    runs-on: ubuntu-latest
    needs: build
    services:
      wiremock:
        image: wiremock/wiremock:2.35.0
        ports:
          - 8080:8080
        options: --health-cmd="curl --silent --fail http://localhost:8080/__admin/health" --health-interval=10s --health-timeout=5s --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Wait for WireMock container to be ready
        run: |
          echo "Waiting for WireMock container to be available"
          until curl --silent --fail http://localhost:8080/__admin/health; do
            echo "Waiting for WireMock to start..."
            sleep 5
          done

      - name: Run tests with coverage
        run: ./gradlew test jacocoTestReport

      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: app/build/reports/jacoco/test/html

  lint:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run Checkstyle
        run: ./gradlew checkstyleMain checkstyleTest

      - name: Upload lint report
        uses: actions/upload-artifact@v3
        with:
          name: checkstyle-report
          path: app/build/reports/checkstyle
